# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: michaelsalafia

# Also define 'vault_users' (`group_vars/staging/vault.yml`, `group_vars/production/vault.yml`)
users:
  - name: "{{ web_user }}"
    groups:
      - "{{ web_group }}"
    keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      - "{{ lookup('file', '~/.ssh/google_compute_engine.pub') }}"
      - https://github.com/digimix.keys
      - https://github.com/michaelsalafia.keys
      - https://github.com/christinecardoso.keys
      - "{{ lookup('file', '~/.ssh/christine_id_rsa.pub') }}"
      # - https://github.com/username.keys
  - name: "{{ admin_user }}"
    groups:
      - sudo
    keys:
      - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      - "{{ lookup('file', '~/.ssh/google_compute_engine.pub') }}"
      - https://github.com/digimix.keys
      - https://github.com/michaelsalafia.keys
      - https://github.com/christinecardoso.keys
      - "{{ lookup('file', '~/.ssh/christine_id_rsa.pub') }}"

web_user: web
web_group: www-data
web_sudoers:
  - "/usr/sbin/service php7.3-fpm *"
